version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=learn
      - MONGO_INITDB_ROOT_PASSWORD=learn

volumes:
  mongodb-data: